[project]
name = "auto-diff"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "jax>=0.5.3",
    "keras>=3.9.1",
    "matplotlib>=3.10.1",
    "mypy>=1.15.0",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "ruff>=0.11.6",
    "pylint>=3.1.0",
    "scikit-learn>=1.6.1",
    "torch>=2.6.0",
    "tqdm>=4.67.1",
]

[tool.ruff.lint.isort]
force-wrap-aliases = true

[tool.ruff.lint]
select = ["E", "F", "B", "ERA"]
extend-select = ["PLC", "PLE", "PLW", "PLR"]

[tool.mypy]
strict = true
