name: Build, Test and Publish

on:
  pull_request:
    types:
      - opened
      - synchronize
  # Same as above
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          git tag
          /bin/bash -x run.sh install

      - name: Lint and format
        run: |
          /bin/bash -x run.sh lint_and_format:ci

      - name: Build
        run: |
          /bin/bash -x run.sh build

      - name: Publish to testpypi
        run: |
          /bin/bash -x run.sh publish:test
        env:
          TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
